### ISSUE TITLE
Dark mode color doesn't sync with toggle button

### ISSUE THREAD

**Issue by TroySigX** [WillPalaia/TrailSafe#89]
Found a corner case where the UI shows dark theme when the dark mode switch is turned off (and vice versa).

Here's the steps to reproduce:
1. Start server and turn on dark mode, the display should be dark theme now.
2. Close the browser.
3. Open the browser again, this time even though the switch is off, the display is still dark theme.

**Comment by WillPalaia** [comment]
Done, review my pull request and test it out to make sure it's all good.
